<?php
print '<div id="cabecalho">
    <div class="logo-search">
      <div class="logo">
        <a href="index.php">
          <img src="assets/cefet.png" alt="">
        </a>
      </div>
      <div class="search">
        <input type="text" placeholder="Pesquisar">
      </div>
    </div>
    <div>
      <ul class="list">
        <li class="feed"><a href="index.php" class="a">Feed</a></li>
        <li class="msg"><a href="mensagens.php" class="a">Mensagens</a></li>
        <li class="notificacoes"><a href="notificacoes.php" class="a">Notificações</a></li>
        <li ><a href="entrar.php"><img src="assets/icone.svg" alt=""></a></li>
        <li ><a href="" class="p1 acessibilidade"><img src="assets/contraste.png" alt=""></a></li>
        <li ><a href="" class="acessibilidade"><img src="assets/fonte.png" alt=""></a></li>
        <li ><a href="" class="acessibilidade"><img src="assets/som.png" alt=""></a></li>
      </ul>
    </div>
   </div>'
?>